version: '3.7'

services:
  pypi-server:
    image: pypiserver/pypiserver:latest
    ports:
      - 8080:8080
    volumes:
      - type: volume
        source: pypi-server
        target: /data/packages
      - ./.htpasswd:/data/.htpasswd
    command: -P /data/.htpasswd -a 'update' /data/packages --overwrite
    restart: always

volumes:
  pypi-server:
